#https://github.com/medlypharmacy/s3-artifacts-action
name: My Workflow

on: [push]

jobs:
  DownloadFileAndUploadToS3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo "Going to download a .zip file of repo...."
          wget https://github.com/PeterBarczi/linux/archive/refs/heads/main.zip
          unzip main.zip
      - run: echo "Transferring to S3.... "
      - uses: medlypharmacy/s3-artifacts-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_s3_bucket_name: ${{ secrets.AWS_S3_BUCKET }}
          source_path: './linux-main/index.html'
          destination_path: "/index.html"
          exclude_repo_from_destination_path: true

